{% set version = "2.2.10" %}
{% set ver = version|replace(".", "_") %}

package:
  name: expat
  version: {{ version }}

source:
  url: https://github.com/libexpat/libexpat/releases/download/R_{{ ver }}/expat-{{ version }}.tar.bz2
  sha256: b2c160f1b60e92da69de8e12333096aeb0c3bf692d41c60794de278af72135a5

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1
{% endif %}
  run_exports:
    # changes soname at major versions, default settings OK
    # https://abi-laboratory.pro/tracker/timeline/expat/
    - {{ pin_subpackage('expat') }}
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
{% if bootstrapping != 'yes' %}
    - cmake  # [win]
    - make  # [unix]
    - libtool  # [unix]
  host:
    - msinttypes  # [win and vc<14]
{% endif %}

test:
  commands:
    - xmlwf -h

about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - mingwandroid
    - msarahan
    - scopatz
