travis:
  secure:
    BINSTAR_TOKEN: LSiOHApwXyiszHkj/4IH5ERJDy9SXmli3AApueK6qkeXv8Q+WHSWQjnLs9JWYA/A8xZLIFP9QgmcwUzKcVgS0MYdMMkL6+8OC1XSv+tgTltudzpB/PrUNaPHsY+UjQ9nIQSIaR6hl7Jb2azk82PwWELYDfyxntZpiM1aFfKmobWss6N6uHD6ie9xdfMW7rNSNSfCGivjqBYhOUseeE4rxZeL8ElHcFbzv6baJX8H5WTsil2r+NpS5NHtSGNShT272R1ejVKz/lM6wz7ZJPiaGaetJBPI5ytJiKelQVJCzhh48yEG8eOY3xt1HW5sV23KKXx82pAU2ijkooOYkqDMXBNgbWj+VsNidgPXdtUK5QVEHjsxfN9CxbLDnK0zKg+vSMZSGRfOrIMk8p4nbVB0MCUTfsSDQwm3jDKeGOuJxGWaMdp6PN1eK852gH0MU0peixVzaCKiRHVtBpIKGJzHCotwU/EJYKxllzQln5w2wx5QSDJIir4frMYASu+21wJNChYmv1pyQCHItfKxv9C6H8782ch1HYVOkdezxBY7OfMszeZ1gjY+2L8YTm9ckPoGO9dFMqfRMhCc3YiLzoZnKPf6cDAnPr+z/2I3zKGWeRwsxDVFwxWc67hCQN/+sguNGHuv9GxRzcZNAUeS1698Wps639Ly731QuoWUbrNdVm8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
